# Generated by Django 4.2.3 on 2024-05-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InsuranceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("sex", models.CharField(max_length=10)),
                ("bmi", models.FloatField()),
                ("children", models.IntegerField()),
                ("smoker", models.CharField(max_length=10)),
                ("region", models.CharField(max_length=15)),
                ("charges", models.FloatField()),
            ],
        ),
    ]
