# Generated by Django 4.2.3 on 2024-05-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurancedata",
            name="region",
            field=models.CharField(
                choices=[("southwest", "Southwest"), ("northwest", "Northwest")],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="insurancedata",
            name="sex",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="insurancedata",
            name="smoker",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], max_length=10
            ),
        ),
    ]
