# Generated by Django 4.2.3 on 2024-05-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "insurance_app",
            "0002_alter_insurancedata_region_alter_insurancedata_sex_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="insurancedata",
            options={
                "verbose_name": "Insurance Data",
                "verbose_name_plural": "Insurance Data",
            },
        ),
        migrations.AddField(
            model_name="insurancedata",
            name="coverage",
            field=models.CharField(default="Standard", max_length=50),
        ),
        migrations.AlterField(
            model_name="insurancedata",
            name="bmi",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="insurancedata",
            name="charges",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
